name = "danogo2023/daken"
version = "1.0.2"
license = "Apache-2.0"
description = "Danogo Aiken Library"

[repository]
user = "danogo2023/daken"
project = "daken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
