name = "Danogo/daken"
version = "1.0.0"
license = "Apache-2.0"
description = "Danogo Aiken Library"

[repository]
user = "Danogo2023"
project = "daken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
