name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    # tags: [ "*.*.*" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      # - name: 🧰 Setup Pages
      #   uses: actions/configure-pages@v2

      - name: 🧰 Install Aiken
        uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.16-alpha

      - name: 📝 Run fmt
        run: aiken fmt --check

      - name: 🔬 Run tests
        run: aiken check -D

      - name: 📘 Generate documentation
        shell: bash
        working-directory: .
        run: aiken docs -o docs

      # - name: 📦 Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: "docs/"
